import type {
  DispatchCall,
  DispatchUnit,
  FullDispatchState,
  HeatmapEvent,
  PatrolGroup,
  TacticalItem,
} from "../types/dispatch";

const now = Math.floor(Date.now() / 1000);
export const mockUnits: DispatchUnit[] = [
  {
    id: "unit-101",
    callsign: "101",
    name: "Nmsh Dev",
    department: "LSPD",
    rank: "Sergeant",
    job: "police",
    status: "AVAILABLE",
    coords: { x: 425, y: -979 },
    vehicle: { label: "Police Cruiser" },
    movementType: "VEHICLE",
    radioChannel: "1",
  },
  {
    id: "unit-102",
    callsign: "102",
    name: "James Carter",
    department: "LSPD",
    rank: "Officer II",
    job: "police",
    status: "ASSIGNED",
    coords: { x: 188, y: -1019 },
    vehicle: { label: "Police Buffalo" },
    movementType: "VEHICLE",
    radioChannel: "1",
    currentCallId: "call-store",
  },
  {
    id: "unit-103",
    callsign: "103",
    name: "Mason Cole",
    department: "LSPD",
    rank: "Officer I",
    job: "police",
    status: "AVAILABLE",
    coords: { x: 439, y: -987 },
    vehicle: { label: "Police Cruiser" },
    movementType: "VEHICLE",
    radioChannel: "1",
  },
  {
    id: "unit-104",
    callsign: "104",
    name: "Nora Hayes",
    department: "LSPD",
    rank: "Officer II",
    job: "police",
    status: "RESPONDING",
    coords: { x: 375, y: -1612 },
    vehicle: { label: "Police Scout" },
    movementType: "MOTORCYCLE",
    radioChannel: "4",
    currentCallId: "call-store",
  },
  {
    id: "unit-105",
    callsign: "105",
    name: "Eli Brooks",
    department: "LSPD",
    rank: "Corporal",
    job: "police",
    status: "ON_SCENE",
    coords: { x: -553, y: -174 },
    vehicle: { label: "Police Cruiser" },
    movementType: "VEHICLE",
    radioChannel: "3",
    currentCallId: "call-panic",
  },
  {
    id: "unit-106",
    callsign: "106",
    name: "Olivia Hart",
    department: "LSPD",
    rank: "Officer I",
    job: "police",
    status: "OUT_OF_SERVICE",
    coords: { x: -304, y: -829 },
    vehicle: { label: "Police Cruiser" },
    movementType: "VEHICLE",
    radioChannel: "1",
  },
];
export const mockGroups: PatrolGroup[] = [
  {
    id: "patrol-adam-1",
    callsign: "ADAM-1",
    leaderId: "unit-101",
    memberIds: ["unit-101", "unit-103"],
    status: "AVAILABLE",
    isGroup: true,
  },
];
export const mockCalls: DispatchCall[] = [
  {
    id: "call-panic",
    code: "10-99",
    title: "Officer Panic",
    description:
      "Emergency activation received from an officer near Del Perro Pier.",
    priority: "PANIC",
    department: "LSPD",
    coords: { x: -1608, y: -1045 },
    street: "Red Desert Ave",
    area: "Del Perro",
    createdAt: now - 18,
    status: "ACTIVE",
    assignedUnits: [
      {
        id: "unit-105",
        callsign: "105",
        name: "Eli Brooks",
        status: "ON_SCENE",
      },
    ],
    respondingUnits: [
      {
        id: "unit-105",
        callsign: "105",
        name: "Eli Brooks",
        status: "ON_SCENE",
      },
    ],
    metadata: {
      panic: true,
      wave: 3,
      timeline: [{ at: now - 18, text: "Panic alert received" }],
    },
  },
  {
    id: "call-store",
    code: "10-15",
    title: "Store Robbery",
    description: "A person is robbing a convenience store and may be armed.",
    priority: "HIGH",
    department: "LSPD",
    coords: { x: 24, y: -1346 },
    street: "Innocence Blvd",
    area: "Strawberry",
    createdAt: now - 74,
    status: "ACTIVE",
    assignedUnits: [
      {
        id: "unit-102",
        callsign: "102",
        name: "James Carter",
        status: "ASSIGNED",
      },
      {
        id: "unit-104",
        callsign: "104",
        name: "Nora Hayes",
        status: "RESPONDING",
      },
    ],
    respondingUnits: [
      {
        id: "unit-104",
        callsign: "104",
        name: "Nora Hayes",
        status: "RESPONDING",
      },
    ],
    metadata: {
      wave: 4,
      timeline: [
        { at: now - 74, text: "Call created" },
        { at: now - 42, text: "102 assigned" },
      ],
    },
  },
  {
    id: "call-shots",
    code: "10-13",
    title: "Shots Fired",
    description: "Multiple gunshots have been reported near the intersection.",
    priority: "HIGH",
    department: "LSPD",
    coords: { x: 327, y: -911 },
    street: "Alta St",
    area: "Pillbox Hill",
    createdAt: now - 46,
    status: "NEW",
    assignedUnits: [],
    respondingUnits: [],
    metadata: {
      details: { weapon: "Carbine Rifle" },
      timeline: [{ at: now - 46, text: "Shots fired report received" }],
    },
  },
  {
    id: "call-medical",
    code: "10-52",
    title: "Medical Emergency",
    description: "A person is unconscious near the main entrance.",
    priority: "MED",
    department: "EMS",
    coords: { x: 307, y: -595 },
    street: "Elgin Ave",
    area: "Pillbox Hill",
    createdAt: now - 132,
    status: "NEW",
    assignedUnits: [],
    respondingUnits: [],
    metadata: { wave: 6, timeline: [{ at: now - 132, text: "Call created" }] },
  },
  {
    id: "call-vehicle",
    code: "10-11",
    title: "Stolen Vehicle",
    description: "A stolen vehicle has been reported near Vespucci Boulevard.",
    priority: "LOW",
    department: "LSPD",
    coords: { x: -1154, y: -739 },
    street: "Vespucci Blvd",
    area: "Vespucci",
    createdAt: now - 305,
    status: "NEW",
    assignedUnits: [],
    respondingUnits: [],
    metadata: { timeline: [{ at: now - 305, text: "Call created" }] },
  },
  {
    id: "history-bank",
    code: "10-90",
    title: "Bank Robbery",
    description:
      "Alarm activation at Fleeca Bank. Suspects fled before units secured the building.",
    priority: "HIGH",
    department: "LSPD",
    coords: { x: 149, y: -1040 },
    street: "Vespucci Blvd",
    area: "Legion Square",
    createdAt: now - 12600,
    closedAt: now - 10800,
    archivedAt: now - 10200,
    status: "ARCHIVED",
    assignedUnits: [],
    respondingUnits: [],
    metadata: {
      notes: [{ at: now - 11000, text: "Scene transferred to investigations" }],
      unitHistory: [
        {
          id: "unit-102",
          callsign: "102",
          name: "James Carter",
          outcome: "ON_SCENE",
        },
      ],
      timeline: [
        { at: now - 12600, text: "Silent alarm received" },
        { at: now - 10800, text: "Call resolved" },
      ],
    },
  },
];
export const mockTactical: TacticalItem[] = [
  {
    id: "tactical-command",
    type: "MARKER",
    points: [[-1040, 149]],
    createdBy: "DISPATCH 01",
    createdAt: now - 320,
  },
  {
    id: "tactical-perimeter",
    type: "ZONE",
    points: [
      [-1017, 100],
      [-1018, 205],
      [-1083, 225],
    ],
    createdBy: "ADAM-1",
    createdAt: now - 240,
  },
  {
    id: "tactical-roadblock",
    type: "ROUTE",
    points: [
      [-1125, 32],
      [-1168, 125],
      [-1196, 238],
    ],
    createdBy: "DISPATCH 01",
    createdAt: now - 110,
  },
];
export const mockHeatmap: HeatmapEvent[] = mockCalls
  .filter((call) => call.coords)
  .map((call) => ({
    coords: call.coords!,
    createdAt: call.createdAt,
    priority: call.priority,
    type: /medical/i.test(call.title)
      ? "MEDICAL"
      : /robbery/i.test(call.title)
        ? "ROBBERY"
        : "VEHICLE",
  }));
export function mockState(dispatcher: boolean): FullDispatchState {
  return {
    calls: mockCalls,
    units: mockUnits.map((unit, index) => ({
      ...unit,
      isDispatcher: dispatcher && index === 0,
    })),
    patrolGroups: mockGroups,
    tacticalItems: mockTactical,
    heatmapEvents: mockHeatmap,
    waves: { first: 3, last: 10 },
    service: {
      department: "LSPD",
      channel: "Los Santos Emergency Communications",
    },
    permissions: {
      dispatcher,
      canBecomeDispatcher: true,
      history: dispatcher,
      tactical: dispatcher,
      heatmap: true,
      tacticalOverlaysVisible: true,
      forceUnitStatus: false,
    },
  };
}
